<link rel="stylesheet" href="<?= $css ?>">
<div class="header">
    <div class="header-inactive">
        <div class="header-line header-line-1"></div>
        <div class="header-line header-line-2"></div>
        <div class="header-line header-line-3"></div>
    </div>
    <div class="header-active">
        <a href="/home">home</a>
        <a href="/experience">experience</a>
        <a href="/references">references</a>
        <a href="/about">about</a>
    </div>
</div>